@default: 
  just --list

test:
  mix test

compile environment="dev": clean update_deps
  MIX_ENV={{environment}} mix compile

update_deps:
  mix deps.get

run_in_shell:
  iex -S mix

format_code:
  mix format

clean:
  mix deps.clean --all

create-database:
  mix ecto.create

create-migration table_name:
  mix ecto.gen.migration {{table_name}}


